apiVersion: v1

kind: Pod

metadata:
  labels:
    app: http-server
  name: http-server

  
spec:
  resources:
    limits:
      cpu: 200m
    requests:
      cpu: 100m

  imagePullSecrets: 
    - name: cloudnative

  containers:
  - name: http-server
    image: registry.cn-hangzhou.aliyuncs.com/maoreus/cloudnative-http-server:1
    volumeMounts:
      - name: http-server-volume
        mountPath: /etc/config
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    ports:        
      - containerPort: 8080

    livenessProbe:
      httpGet:    
        path: /healthz    
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    
    readinessProbe:
        httpGet:      
          path: /healthz      
          port: 8080      
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
    
    lifecycle:
        preStop:
          exec:
            command: [ "/bin/sh","-c","http-server -s quit; while killall -0 http-server; do sleep 1; done" ]
            
    volumes:
    - name: http-server-volume
      configMap:
        name: http-server-config
        
    
        
    
    
